name: WPT_mMTC
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - pip
  - pip:
    - jupyter
    - mosek
    - numpy
    - scipy
    - matplotlib
    - cvxpy
    - black
    - flake8
